apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dyndns
            image: busybox
            imagePullPolicy: IfNotPresent
            command: |
              IP=`curl --ipv4 -s http://icanhazip.com/` & \
              curl -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -H "Accept: application/json" -X "PATCH" -i "https://api.dnsimple.com/v2/$ACCOUNT_ID/zones/$ZONE_ID/records/$RECORD_ID" -d "{\"content\":\"$IP\"}"
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: token

              - name: ACCOUNT_ID
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: account

              - name: ZONE_ID
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: zone

              - name: RECORD_ID
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: record
                     
          restartPolicy: OnFailure
