apiVersion: batch/v1
kind: CronJob
metadata:
  name: dyndns
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dyndns
            image: golang
            command: 
              - go run /main.go 
                
            volumeMounts:
              - name: gofile
                mountPath: "/main.go"

            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: token

              - name: ACCOUNT_ID
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: account

              - name: ZONE_ID
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: zone

              - name: RECORD_ID
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: record

            volumes:
              - name: gofile
                configMap:
                  name: ddnsgo
                  items:
                    - key: main.go
                      path: main.go
                     
          restartPolicy: OnFailure
