apiVersion: batch/v1
kind: CronJob
metadata:
  name: dyndns
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: gofile
              configMap:
                name: ddnsgo
                items:
                  - key: main.go
                    path: main.go

          containers:
          - name: dyndns
            image: oonray/dyndns
            env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: token

              - name: ACCOUNT_ID
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: account

              - name: ZONE_ID
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: zone

              - name: RECORD_ID
                valueFrom:
                  secretKeyRef:
                    name: dyndns
                    key: record
                    
          restartPolicy: OnFailure
