apiVersion: apps/v1
kind: Deployment
metadata:
    name: ddns
    labels:
      app: ddns
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ddns
    template:
        metadata:
            labels:
                app: ddns
        spec:
          dnsConfig:
              nameservers:
                - 192.168.10.164
          restartPolicy: OnFailure
          containers:
            - name: dyndns
              image: oonray/ddns:latest
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: dyndns
                      key: token

                - name: ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: dyndns
                      key: account

                - name: ZONE_ID
                  valueFrom:
                    secretKeyRef:
                      name: dyndns
                      key: zone

                - name: RECORD_ID
                  valueFrom:
                    secretKeyRef:
                      name: dyndns
                      key: record
                    
