apiVersion: batch/v1
kind: CronJob
metadata:
  name: dyndns
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnError
          containers:
            - name: dyndns
              image: oonray/ddns:latest
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: dyndns
                      key: token

                - name: ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: dyndns
                      key: account

                - name: ZONE_ID
                  valueFrom:
                    secretKeyRef:
                      name: dyndns
                      key: zone

                - name: RECORD_ID
                  valueFrom:
                    secretKeyRef:
                      name: dyndns
                      key: record
                    
