name: Create Munin Zip
on: [push]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'munin.zip'
          exclusions: '*.git*'
          type: zip

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
            name: Munin
            tag: 1.1
            artifacts: "munin.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
